//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::AssetType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "asset")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub ticker_symbol: String,
    pub asset_type: AssetType,
    pub name: String,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))")]
    pub current_price: Decimal,
    pub unit: String,
    pub last_update: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::investment_transaction::Entity")]
    InvestmentTransaction,
    #[sea_orm(has_many = "super::portfolio::Entity")]
    Portfolio,
}

impl Related<super::investment_transaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InvestmentTransaction.def()
    }
}

impl Related<super::portfolio::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Portfolio.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
