//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod asset;
pub mod category;
pub mod insight;
pub mod investment_transaction;
pub mod portfolio;
pub mod sea_orm_active_enums;
pub mod transaction;
pub mod user;
pub mod wallet;
