//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::asset::Entity as Asset;
pub use super::category::Entity as Category;
pub use super::insight::Entity as Insight;
pub use super::investment_transaction::Entity as InvestmentTransaction;
pub use super::portfolio::Entity as Portfolio;
pub use super::transaction::Entity as Transaction;
pub use super::user::Entity as User;
pub use super::wallet::Entity as Wallet;
